import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Layout as RootLayout } from '@/layouts/root';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Aboba',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RootLayout>
        <body className={inter.className}>{children}</body>
      </RootLayout>
    </html>
  );
}
