import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Layout as RootLayout } from '@/layouts/root';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Aboba',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RootLayout>
        <body className={inter.className}>
          <div className={'flex align-middle justify-between p-2 px-4 h-20'}>
            <div className={'flex space-x-4'}>
              <Image
                width={50}
                height={50}
                src="/pepe-dancing-1.gif"
                alt="pepe-dancing-1"
              />
              <div className="max-w-5xl items-center justify-between font-mono text-sm flex">
                <p className="flex w-full justify-center from-zinc-200 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit rounded-xl border bg-gray-200 p-4">
                  <code className="font-mono font-bold">/home</code>
                </p>
              </div>
            </div>
            <Image
              width={50}
              height={50}
              src="/pepe-dancing-2.gif"
              alt="pepe-dancing-2"
            />
          </div>
          {children}
        </body>
      </RootLayout>
    </html>
  );
}
